sudo: required

language: python
cache: pip
python:
- '3.6'

services: docker
install: docker-compose -f test.yml build
script: docker-compose -f test.yml -p ci run test python -m pytest --cov=web/ tests && apk update && apk add git && codecov
after_success:
  - codecov
