sudo: required

language: python
cache: pip
python:
- '3.6'

services: docker
install: docker-compose -f test.yml build
script: docker-compose -f test.yml run test /bin/bash -c "curl -s https://codecov.io/env -o cc_env.sh; bash cc_env.sh; python -m pytest --cov=web/ tests; curl -s https://codecov.io/bash -o cc_bash.sh; bash cc_bash.sh -t xxxx-xxxxxx-xxxx"
