sudo: required

language: python
cache: pip
python:
- '3.6'

services: docker
install: docker-compose -f test.yml -p ci build
script: docker-compose -f test.yml -p ci run test sh -c "python -m pytest --cov=web --cov=indexer tests && pip freeze && codecov"
